### ISSUE TITLE
UI fails when Knownledge Bases for Bedrock is configured with a non S3 vector stiore and use case configuration is set to display source links

### ISSUE THREAD

**Issue by knihit** [aws-solutions/generative-ai-application-builder-on-aws#131]
**Describe the bug**
A use case configured with non s3 vector store and display source link enabled, throws an error.

**To Reproduce**
Steps to reproduce the behavior.

Configure a use case with Knowledge bases for Bedrock. Configure a non S3 vector store. Create a use case with RAG and use this knowledge base. Also configure display source links. The chat UI after the first response fails and shows a white screen.

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: v2.0.0
- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by knihit** [comment]
We are working on fixing this issue.

**Comment by tabdunabi** [comment]
This issue has been resolved in GAAB v2.0.1.
