### ISSUE TITLE
Configuring a guard rail has no effect on LLM response.

### ISSUE THREAD

**Issue by knihit** [aws-solutions/generative-ai-application-builder-on-aws#132]
**Describe the bug**
Configure a guardrail when creating a use case. To test, ask questions that the guardrail should filter. use case continues to respond on filtered topics.

**To Reproduce**
Steps to reproduce the behavior.

Configure a guardrail when creating a use case from the deployment dashboard. The Guardrail was tested from the Bedrock console and works as per the configuration. But when using it through the use case, it does not seem to have any effect. The use case continues to respond on blocked topics.

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: v2.0.0
- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by knihit** [comment]
We are working on the fix for this issue.

**Comment by tabdunabi** [comment]
This issue has been resolved in GAAB v2.0.1.
