### ISSUE TITLE
[Question] Slack Integration

### ISSUE THREAD

**Issue by bogdankatishev** [aws-solutions/generative-ai-application-builder-on-aws#150]
Hello,

What would be the best way to integrate the text use-case prompt with slack?
So that users could pass the questions through a (slack) bot to the specific use-case created through the UI.

**Comment by knihit** [comment]
Thank you for reach out @bogdankatishev. When you deploy the text use case (which is a CloudFormation template behind the scene), the outputs tab in the AWS console --> CloudFormation service  --> (Text Use case stack name) has the websocket endpoint to invoke. We publish information on the WebSocket payload in our implementation guide here - https://docs.aws.amazon.com/solutions/latest/generative-ai-application-builder-on-aws/api-reference.html#chat-use-case-2. Please let us know if this information helps building the slack app to do the integration.
