### ISSUE TITLE
don't use a static login UI and use the Cognito UI for more functionalities

### ISSUE THREAD

**Issue by jeffsec-aws** [aws-solutions/generative-ai-application-builder-on-aws#23]
**Is your feature request related to a problem? Please describe.**
Yes as it will be an easier way to answer also issues #4 and #5 

**Describe the feature you'd like**
Use the Cognito Hosted UI instead of a static login UI with the pattern used at https://github.com/awslabs/cognito-at-edge

This will allow you to support natively :
- Identity Federation from social login
- Identity Federation from Enterprise IdP
- multi factor authentication
- password reset and recovery
- Self-service sign-up

**Comment by jeffsec-aws** [comment]
or at least use: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html

**Comment by knihit** [comment]
Thank you for the suggestion. The solution uses Amplify signin UI component. We will do a due diligence to compare our current implementation and Cognito hosted UI, evaluate the pros/ cons and make a decision for future iterations. Adding this as a spike for our future sprints.

**Comment by mukitmomin** [comment]
As of [v2.0.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v2.0.0), cognito hosted UI is used for the login UI.
