### ISSUE TITLE
Add language parameter for Kendra search

### ISSUE THREAD

**Issue by brunedv** [aws-solutions/generative-ai-application-builder-on-aws#24]
**Is your feature request related to a problem? Please describe.**
When you create a Kendra index in another language than English, it is not possible to query the knowledge database. 

**Describe the feature you'd like**
It will be great to have a language parameter when we configure the connection to the Kendra index (in the Rag additional parameters) or the application detects the language of the index.

**Comment by knihit** [comment]
@brunedv thank you for reaching out. This is a great feature request, we will add it to our backlog and as we plan our iterations, we will include this in one of our future releases.

For your feature request, do you think the browser's locale would work as language input or you think we would have a separate input to capture language code in the chat application.

**Comment by brunedv** [comment]
@knihit , both work for me or you might configure the language at the creation of the chat application.

**Comment by tiagoReichert** [comment]
I'm on the same issue here.

@knihit Do you have any expectation on when to launch it? 
Do you know if we can change this by ourselves in the lambda function created for the ChatBot that queries Kendra?

**Comment by brunedv** [comment]
> I'm on the same issue here.
> 
> @knihit Do you have any expectation on when to launch it? Do you know if we can change this by ourselves in the lambda function created for the ChatBot that queries Kendra?

Hi @tiagoReichert , it is possible to modify the lambda function. You have to add a specific attribute_filter here: https://github.com/aws-solutions/generative-ai-application-builder-on-aws/blob/b2dac0fe79499d70c2bd6036abe09b87ad2f3202/source/lambda/chat/shared/knowledge/kendra_retriever.py#L72

`
attribute_filter: Optional[Dict] = {"EqualsTo": {      
                "Key": "_language_code",
                "Value": {
                    "StringValue": "fr"
                    }
                }}
`

**Comment by mukitmomin** [comment]
Hi @brunedv and @tiagoReichert language based Kendra query is now supported with the release of [ v1.3.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v1.3.0) with PR #53. For details on how to implement it, please refer to our [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/generative-ai-application-builder-on-aws/customization-guide.html#kendra-attribute-filters).
