### ISSUE TITLE
CORS error after deployment

### ISSUE THREAD

**Issue by canivel** [aws-solutions/generative-ai-application-builder-on-aws#25]
**Describe the bug**
After deploying the cloudformation returns error loading deployments and also to create deployments 

**To Reproduce**
install de cloudformation from the solution library link

**Expected behavior**
the admin open show 0 deployments, instead of infinity loading, and without CORS error (preflight)

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0] 
- [x] 1.1.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0276) - Generative AI Application Builder on AWS Solution. Version v1.0.0".

- [ x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

Access to XMLHttpRequest at 'https://x.execute-api.us-east-1.amazonaws.com/prod/deployments' from origin 'https://x.cloudfront.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by mukitmomin** [comment]
HI Canivel, thanks for raising this issue. I had a couple of clarifying questions:
1. which browser are you using?
2. does the browser console show any other error?

**Comment by canivel** [comment]
Chrome last version:
![image](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/201984/f00bb0f0-88cc-4226-8325-711f31f4d407)

**Comment by mukitmomin** [comment]
Are you using the default `-admin` user that the cloudformation stack created or is this a new user you added via cognito?

**Comment by canivel** [comment]
default user

**Comment by mukitmomin** [comment]
thats quite odd. i deployed the latest template ([v1.1.1](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?&templateURL=https://solutions-reference.s3.amazonaws.com/generative-ai-application-builder-on-aws/latest/generative-ai-application-builder-on-aws.template)) from the solution landing page and am not seeing it. I suggest trying either of the two things below to see what happens:

1. redeploy but using the `v1.1.1` [template](https://solutions-reference.s3.amazonaws.com/generative-ai-application-builder-on-aws/latest/generative-ai-application-builder-on-aws.template)

1. On a existing deployment:
      - navigate to the CloudFront console
      - locate the distribution associated with your deployment (Origins column in the distributions table should have the stack name at the start)
      - Select Behaviors, and click Edit
      - Under the `Cache key and origin requests` section find the `Response headers policy` section
      - click CSP header policy, and change it from the custom CSP policy header created by the solution, and select the SimpleCORs managed policy.
      - save changes (might need to wait a couple mins for changes to propagate) and try visiting the deployment dashboard UI.
  
 If the same issue arrises, then it is likely not a CORS issue. Something else could be going on.

**Comment by canivel** [comment]
Instaling 1.1.1 and will revert back with findings, the one in solution library looks like is 1.1.0
![image](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/201984/12bb957d-183e-466e-b137-671453bc2eb5)

**Comment by tabdunabi** [comment]
@mukitmomin have you tried deploying using the same browser(s) @canivel used, to try reproducing the issue?

**Comment by mukitmomin** [comment]
> Instaling 1.1.1 and will revert back with findings, the one in solution library looks like is 1.1.0 ![image](https://user-images.githubusercontent.com/201984/284364590-12bb957d-183e-466e-b137-671453bc2eb5.png)

The assets were updated a few days ago, the landing page should have been updated this morning. Reloading should show the latest. 

I couldn't replicate the issue with a fresh deployment on Chrome. I'm looking more into the issue. I'll get back to you as soon as i can find out more info

**Comment by canivel** [comment]
Yes, Chrome was used all times. Safari and Firefox used to test it. Tried in 2 different accounts(clean) and 2 different regions, all the same result.
I also test to SimpleCors and Preflight Cors on the distributions, waited for it to fully deploy and still same CORS issue... maybe is some issue in the API Gateway CORS?

**Comment by knihit** [comment]
@canivel are you behind any firewall, proxy or VPN? If so, are you able to test it from a machine that does not have such constraints.

**Comment by jamesnixon-aws** [comment]
Could not reproduce, please re-open if issue persists.
