### ISSUE TITLE
Incorrect README doucmentation

### ISSUE THREAD

**Issue by daviddurairaj** [aws-solutions/generative-ai-application-builder-on-aws#26]
**Describe the bug**
The READMEs under both source/ui-chat and source/ui-deployment for running and building the UI locally have a bug in the sample code for creating the runtimeConfig file where the file extension is `.js` instead of `.json`
~`touch source/ui-deployment/public/runtimeConfig.js`~
`touch source/ui-deployment/public/runtimeConfig.json`

**To Reproduce**
If user mistakenly uses wrong file extension, npm commands will work and not error out, but localhost won't load anything. It basically isn't immediately obvious what the issue is if a user blindly copy-pasted code.

**Expected behavior**
When user runs `npm start`, website should load locally in browser. 

**Please complete the following information about the solution:**

- [-] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0276) - Generative AI Application Builder on AWS Solution. Version v1.0.0".

- [-] Region: [e.g. us-east-1]
- [No] Was the solution modified from the version published on this repository?
- [-] If the answer to the previous question was yes, are the changes available on GitHub?
- [-] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [-] Were there any errors in the CloudWatch Logs?

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ihmaws** [comment]
Thanks @daviddurairaj, good catch!

We'll get that updated for our next release.

**Comment by tabdunabi** [comment]
Fixed in v1.2.0.
