### ISSUE TITLE
Initial deployment failed to create 	UseCasesTableXXX based on KMS validation error: com.amazonaws.services.kms.model.NotFoundException: Key 'arn:aws:kms:us-east-1:xxx:key/xxxx' does not exist

### ISSUE THREAD

**Issue by JeremyJonas** [aws-solutions/generative-ai-application-builder-on-aws#29]
**Describe the bug**
Very first attempt to deploy the solution failed, after following the steps (stack name and admin email), the stack failed to deploy the nested stack "DeploymentPlatformStorageDeploymentPlatformStorageNestedStackDe-GKN9DKVAKLTC" based on failure to create the UseCasesTableXXX, resulting in following error:

> Resource handler returned message: "KMS validation error: com.amazonaws.services.kms.model.NotFoundException: Key 'arn:aws:kms:us-east-1:xxx:key/xxx' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: xxx; Proxy: null) (Service: DynamoDb, Status Code: 400, Request ID: XXX)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)

**To Reproduce**
Deploy into us-east-1 with only specifying the Stack Name and Admin Email properties.

**Expected behavior**
Expect to deploy.

**Please complete the following information about the solution:**

- [x] Version v1.1.1
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? CloudFormation error above is sufficient

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by knihit** [comment]
@JeremyJonas This is an intermittent issue that we noticed happen as well. The KMS used for the DynamoDB table is created by the DynamoDB service but sometimes takes longer than expected and hence the error. We continue to monitor the issue. I would suggest run it again in us-east-1 (the region where you were trying to deploy) and it should deploy fine. Please let us know if it fails consistently.
