### ISSUE TITLE
Option to use Bedrock knowledge base instead of kendra

### ISSUE THREAD

**Issue by jasg00** [aws-solutions/generative-ai-application-builder-on-aws#43]
**Is your feature request related to a problem? Please describe.**
I tested the app and it works fine, but kendra is way to expensive as source knowledge base where there are millions of documents to index.

**Describe the feature you'd like**
It would be great to also be able to choose Bedrock knowledge base.

**Comment by tabdunabi** [comment]
@jasg00 Thank you for reaching out. This is a highly requested feature. We already have it in our backlog and as we plan our iterations, we will include this in one of our future releases.

**Comment by mukitmomin** [comment]
As of [v2.0.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v2.0.0), Bedrock KnowledgeBase is available.
