### ISSUE TITLE
Additional permissions are required

### ISSUE THREAD

**Issue by ybezsonov** [aws-solutions/generative-ai-application-builder-on-aws#45]
**Describe the bug**
I deployed the solution to my AWS account. I started to create the first Deployment, but it failed due to permissions issue for generative-ai-application-bui-CfnDeployRole*. I added "iam:PassRole" and "cloudformation:CreateStack" and next deployment was successful.
When I tried to updated deployment it failed due to missing "cloudformation:UpdateStack" permission. I added it and redeployed Stack in CloudFormation console, because the stack was not visible anymore in the App Deployments. Redeployment was successful.

The final policy is below.  
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Statement1",
			"Effect": "Allow",
			"Action": [
				"iam:PassRole",
				"cloudformation:CreateStack",
				"cloudformation:UpdateStack"
			],
			"Resource": "*"
		}
	]
}

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**

- [ 1.2.2] Version: 

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0276) - Generative AI Application Builder on AWS Solution. Version v1.0.0".

- [ us-west-2 ] Region: [e.g. us-east-1]
- [no, as is ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [in CloudFormation ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by tabdunabi** [comment]
Thank you @ybezsonov for reporting this. We are aware of this issue, and will be releasing a patch today or tomorrow.

You may also want to add `cloudformation:DeleteStack`, to be able to delete the stack.

**Comment by ybezsonov** [comment]
Thank you!

**Comment by tabdunabi** [comment]
@ybezsonov we have just released v1.2.3, which addresses this issue.
