### ISSUE TITLE
OpenAPI doc for the REST API?

### ISSUE THREAD

**Issue by mlconnor** [aws-solutions/generative-ai-application-builder-on-aws#48]
Is there a swagger or OpenAPI doc for the REST API?

**Comment by jamesnixon-aws** [comment]
Hi Michael,
You can export an OpenAPI/Swagger file for the API from API Gateway once the solution is deployed (see [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html))
Additionally, the API is documented in the [implementation guide](https://docs.aws.amazon.com/solutions/latest/generative-ai-application-builder-on-aws/api-reference.html) if you wish to view it before deployment.

**Comment by mlconnor** [comment]
thanks James. that's perfect
