### ISSUE TITLE
Ability to work with Bedrock Agents

### ISSUE THREAD

**Issue by sathishc** [aws-solutions/generative-ai-application-builder-on-aws#49]
**Describe the feature you'd like**
Provide a builder client to connect to a Bedrock Agent with agentId and agentAliasId. This will allow usage of knowledge bases and action groups with this systems

**Additional context**
Bedrock Agents allow LLM to reason and integrate with real time information.

**Comment by mukitmomin** [comment]
@sathishc Thank you for reaching out. Bedrock Agent integration is a highly requested feature. We already have it in our backlog and as we plan our iterations, we will include this in one of our future releases.

**Comment by jamesnixon-aws** [comment]
Feature has been implemented in release v2.1.0
