### ISSUE TITLE
Allow option to not enable prompt customization

### ISSUE THREAD

**Issue by subha-aws** [aws-solutions/generative-ai-application-builder-on-aws#6]
**Is your feature request related to a problem? Please describe.**
I do not want my users to go change the prompt. 
While deploying, allow an option to select whether we should alloww the prompt to be changed.

**Additional context**

**Comment by knihit** [comment]
@subha-aws thank you for the feedback, we will add this to our backlog and as we plan our future iterations we will try to include them in the upcoming releases. Keeping the ticket open to get feedback/ voting and help us prioritize features.

**Comment by mukitmomin** [comment]
As of [v2.0.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v2.0.0), prompt customization is available in the deployment wizard.
