### ISSUE TITLE
Conversation with RAG enabled Claude V2 is ending abruptly

### ISSUE THREAD

**Issue by wzr1337** [aws-solutions/generative-ai-application-builder-on-aws#66]
**Describe the bug**
I have set up a RAG enabled Bedrock ClaudeV2 application, filled the Kendra DB with content and I am now interacting with the newly deployed stack. The Application stops streaming into the browser abruptly, after being idle for some time (latency between query and response is very notable). Upon debugging, I can see that the WebSocket sends a `##END_CONVERSATION` message, so the client behavior is correct. I suspect a lambda timeout or something similar to block here, but I was unable to dive deep enough which lambda might be timing out. As some handler send the `##END_CONVERSATION` message, I guess it is second level.

**To Reproduce**
Ask the system to generate a text with more than 1000 words

**Expected behavior**
I would expect the system to stream all the response data before ending the conversation.

**Please complete the following information about the solution:**

- [v1.3.1] Version: [e.g. v1.0.0]
- [us-east-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![screenshot](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/3704301/fe15ba8c-2776-4b57-bcee-1154df9202bf)

**Additional context**
CloudWatch logs:

```text
START RequestId: 52cbce78-1724-4cbb-a104-91182945da59 Version: $LATEST
--
/opt/python/aws_lambda_powertools/metrics/metrics.py:129: UserWarning: No application metrics to publish. The cold-start metric may be published if enabled. If application metrics should never be empty, consider using 'raise_on_empty_metrics'
self.provider.flush_metrics(raise_on_empty_metrics=raise_on_empty_metrics)
{     "level": "INFO",     "location": "generate:130",     "message": "Prompt for LLM: \n\nHuman: You are a friendly AI assistant. You provide answers only based on the provided reference passages.\n\nHere are reference passages in <references></references> tags:\n<references>\n{context}\n</references>\n\nCarefully read the references above and thoughtfully answer the question below. If the answer can not be extracted from the references, then respond with \"Sorry I don't know\". It is very important that you only use information found within the references to answer. Try to be brief in your response.\n\nHere is the current chat history:\n{chat_history}\n\nQuestion: {question}\n\nAssistant:",     "timestamp": "2024-03-05 08:58:34,252+0000",     "service": "BEDROCK_CHAT",     "xray_trace_id": "1-65e6deb9-ebf1a943fcc1ae4992122783" }
{     "_aws": {         "Timestamp": 1709629114252,         "CloudWatchMetrics": [             {                 "Namespace": "Langchain/LLM",                 "Dimensions": [                     [                         "service"                     ]                 ],                 "Metrics": [                     {                         "Name": "LangchainQueries",                         "Unit": "Count"                     }                 ]             }         ]     },     "service": "GAABUseCase-15091dff",     "LangchainQueries": [         1     ] }
{     "_aws": {         "Timestamp": 1709629130051,         "CloudWatchMetrics": [             {                 "Namespace": "AWS/Kendra",                 "Dimensions": [                     [                         "service"                     ]                 ],                 "Metrics": [                     {                         "Name": "KendraQueries",                         "Unit": "Count"                     },                     {                         "Name": "KendraFetchedDocuments",                         "Unit": "Count"                     },                     {                         "Name": "KendraProcessingTime",                         "Unit": "Seconds"                     }                 ]             }         ]     },     "service": "GAABUseCase-15091dff",     "KendraQueries": [         1     ],     "KendraFetchedDocuments": [         5     ],     "KendraProcessingTime": [         0.5714249610900879     ] }
/opt/python/aws_lambda_powertools/metrics/metrics.py:129: UserWarning: No application metrics to publish. The cold-start metric may be published if enabled. If application metrics should never be empty, consider using 'raise_on_empty_metrics'
self.provider.flush_metrics(raise_on_empty_metrics=raise_on_empty_metrics)
{     "_aws": {         "Timestamp": 1709629157170,         "CloudWatchMetrics": [             {                 "Namespace": "Langchain/LLM",                 "Dimensions": [                     [                         "service"                     ]                 ],                 "Metrics": [                     {                         "Name": "LangchainQueryProcessingTime",                         "Unit": "Seconds"                     }                 ]             }         ]     },     "service": "GAABUseCase-15091dff",     "LangchainQueryProcessingTime": [         42.9008150100708     ] }
/opt/python/aws_lambda_powertools/metrics/provider/base.py:209: UserWarning: No application metrics to publish. The cold-start metric may be published if enabled. If application metrics should never be empty, consider using 'raise_on_empty_metrics'
self.flush_metrics(raise_on_empty_metrics=raise_on_empty_metrics)
END RequestId: 52cbce78-1724-4cbb-a104-91182945da59
REPORT RequestId: 52cbce78-1724-4cbb-a104-91182945da59	Duration: 43881.57 ms	Billed Duration: 43882 ms	Memory Size: 256 MB	Max Memory Used: 201 MB

```

**Comment by wzr1337** [comment]
I just checked the Lambda that I pulled the log from and its timeout is set to 15 min, so it should not be the issue

**Comment by wzr1337** [comment]
I changed the deployment settings to NOT use streaming and I get the same result: Corrupted response ending in the middle of the response.

I also tried Claude V2 and V2.1, both have the same issue

**Comment by wzr1337** [comment]
I seem to have found the issue.. It is a too tighly set `max_tokens_to_sample` based on `DEFAULT_MAX_TOKENS_TO_SAMPLE` by changing it to 4096 the response does not get canceled anymore

**Comment by ihmaws** [comment]
Hi @wzr1337, thanks for the report and for taking the time to work through a detailed analysis of the issue.

As you've identified, many LLMs come with the ability to truncate/cap the number of output tokens generated. One of the primary things this helps to do is control costs by providing an upper bound on the number of output tokens generated by the model (output tokens are substantially more costly than input tokens).

For the anthropic family of models this can be controlled by a model parameter called `max_tokens_to_sample` (for their text completion API).

At the time this integration was first built, the default value for this parameter used by Anthropic's API was `256`, so we chose to match this. This may have changed since the first release, so we will have a look and reassess for our next release.

That being said, the solution allows for customers to override any of the default model parameters and provide their own. You can do this at deployment time by setting an advanced model parameter at the model selection step (see example screenshot below). The parameters supported depends on the specific model used, so consult the model documentation.

## Adding Advanced Parameters:
<img width="1339" alt="image" src="https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/111378641/2cc7c0b4-3e3c-4015-8713-3ee89bde49a4">
