### ISSUE TITLE
support for query of non-english documents

### ISSUE THREAD

**Issue by michlin0825** [aws-solutions/generative-ai-application-builder-on-aws#68]
**Describe the feature you'd like**
requesting support for inquiry of non-english documents indexed in Kendra, with configuration options during the GenAI application setup. 

**Additional context**
I have many non-English documents already indexed in Kendra. I can search those inside Kendra when specifying the default language of the source documents (as in captured screenshot). I wish to achieve the same result using the GenAI application builder, taking advantage of the LLM models in Bedrock. 

<img width="1379" alt="1_Query_Non_English_Doc_Possible_Inside_Kendra" src="https://github.com/aws-solutions/generative-ai-application-builder-on-aws/assets/51706220/016525e6-1ca0-4946-9176-898117935bc1">

**Comment by mukitmomin** [comment]
Hi @michlin0825 that for opening this issue and for using Generative AI Application Builder on AWS.

We are actively looking into the best way to expose knowledge base specific configuration parameters, such as language to the wizard ui. With the release of [v1.3.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v1.3.0) with PR https://github.com/aws-solutions/generative-ai-application-builder-on-aws/pull/53 we have added backend support to specify the language for the kendra index. After deploying a chat use case, you can update the AWS Systems Manager (SSM) Parameter Store parameter for the deployment to specify an [AttributeFilter](https://docs.aws.amazon.com/kendra/latest/APIReference/API_AttributeFilter.html) JSON object that will be picked up by Kendra. 

To locate the SSM parameter, note down the use case ID for your deployment, which is the last 8 digits of the name of the CloudFormation stack for the chat deployment. Navigate to the AWS Console > Systems Manger > Parameter Store, and locate the `/gaab-ai/use-case-config/<use-case-id>`. Then follow the instructions on our [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/generative-ai-application-builder-on-aws/customization-guide.html#kendra-attribute-filters) to specify the language parameter.

**Comment by mukitmomin** [comment]
As of release v2.0.0, the attribute filter is available in the knowledge base step of the wizard, and can be used to configure the language code. Closing this issue. Please reach out if you have any other questions.
