### ISSUE TITLE
Create ability to display formatted answers from model

### ISSUE THREAD

**Issue by joshkurz** [aws-solutions/generative-ai-application-builder-on-aws#7]
I would like to display formatted answers if the model sends formatting information. Like ```<ul><li>``` or something along those lines. 
I would like to see bullet lists and more paragraphs vs just walls of text.

If the model sends formatting characters we should display them and allow for the formatting in the UI.

Or we should create another prompt that formats text and send the output through that.

**Comment by tabdunabi** [comment]
Hi @joshkurz, thank you for creating this feature request. 
We already have `displaying formatted answers` at the top of our prioritized list of feature, and working on releasing it in the near future.

**Comment by joshkurz** [comment]
Awesome! TY. I'll go ahead and close this out.
