### ISSUE TITLE
support for claude 3 / sonnet & haiku

### ISSUE THREAD

**Issue by michlin0825** [aws-solutions/generative-ai-application-builder-on-aws#79]
Is there roadmap to include Claude 3 models (sonnet & haiku for now, and perhaps opus in the future) as options in the solution stack?  thanks.

**Comment by ihmaws** [comment]
Hi @michlin0825, thanks for the question!

We are hoping to provide support very soon! I will tag this issue when the models are available.

**Comment by ihmaws** [comment]
Hey @michlin0825 , thanks for the issue!

The solution has been updated with the latest Bedrock text models including Anthropic's Haiku and Sonnet as well as Mistral AI's 7B, 8x7B, and Large models.

See [release notes](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v1.4.0) for a look at the additional contents of the release.

We'll look to support Opus once released.

Thanks again!
