### ISSUE TITLE
UI/Backend misalignment of prompt limit enforcement

### ISSUE THREAD

**Issue by OmarRad** [aws-solutions/generative-ai-application-builder-on-aws#80]
**Describe the bug**
The prompt character limits in the UI are currently hard-coded, are too small, and do not align with the actual limits of the LLM in use.

**To Reproduce**
Input a prompt larger than 2000 characters

**Expected behavior**
The prompt limit enforced on the UI aligns with the limits of the LLM in use.

**Please complete the following information about the solution:**

- Version: [v1.3.0]

**Comment by ihmaws** [comment]
Released as of [v1.4.0](https://github.com/aws-solutions/generative-ai-application-builder-on-aws/releases/tag/v1.4.0)
